name       : byobu
version    : '5.117'
release    : 2
source     :
    - https://launchpad.net/byobu/trunk/5.117/+download/byobu_5.117.orig.tar.gz : 64b0deac161a1d979e656052e23b13496c2d262fd7a069abddd21afbc7d0fca2
license    : GPL-3.0
component  : system.utils
summary    : Byobu is an enhancement for the GNU Screen or Tmux
description: |
    Byobu includes an enhanced profile, configuration utilities, and system status notifications for the GNU screen window manager as well as the Tmux terminal multiplexer.
rundeps    :
    - tmux
    - newt
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
