name       : byobu 
version    : 5.113
release    : 1
source     :
    - https://launchpad.net/byobu/trunk/5.113/+download/byobu_5.113.orig.tar.gz : 2a5aca3fcc1ab7066e4246c1b540c6ab7b0bc235be0d61a5dd4f1091074194ee
license    : GPL-3.0
component  : system.utils
summary    : Byobu is an enhancement for the GNU Screen or Tmux
description: |
    Byobu includes an enhanced profile, configuration utilities, and system status notifications for the GNU screen window manager as well as the Tmux terminal multiplexer.
rundeps    :
    - tmux
    - newt
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
